version: '2'
services:

  service:
    image: 801351377084.dkr.ecr.us-west-1.amazonaws.com/avanti-container:r_master_df02ecbfed8d542e53834cf3ed059a1817299739
    entrypoint: ["/home/avanti/bin/avanti-server"]
    command: ["--port","8080","-v"]
    ports:
      - "8080:8080"
    volumes:
      - "~/.aws:/home/avanti/.aws"

  helloworld:
    image: buoyantio/helloworld
    command: ["-addr=:7777", "-text=Hello"]
    ports:
      - "7777:7777"

  traefik:
    image: traefik

