################################################################
# Global configuration
################################################################
logLevel = "DEBUG"
################################################################
# Web configuration backend
################################################################
[web]
address = ":8080"
################################################################
# File configuration backend
################################################################
[dynamodb]
TableName = "traefik"
Watch = true
RefreshSeconds = 15
Region = "us-west-1"
