################################################################
# Global configuration
################################################################
logLevel = "DEBUG"
################################################################
# Web configuration backend
################################################################
[web]
address = ":8080"
################################################################
# File configuration backend
################################################################
[file]
################################################################
# rules
################################################################
 [backends]
   [backends.backend2]
     [backends.backend2.LoadBalancer]
       method = "drr"
     [backends.backend2.servers.server1]
       url = "http://avanti-824:8080/"
     [backends.backend2.servers.server2]
       url = "http://avanti-825:8080/"
  [frontends]
   [frontends.frontend2]
   backend = "backend2"
   passHostHeader = true
     [frontends.frontend2.routes.test_2]
     rule = "PathPrefix: /avanti"
